version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kinesis-data-stream-fraud-detection"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1avm45auuqgwh"
s3_prefix = "kinesis-data-stream-fraud-detection"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FraudDetectorID=\"transaction_fraud_detector\""
image_repositories = []
